import { test } from 'node:test';
import assert from 'node:assert/strict';
import { handleContact } from '../server/contact-handler.js';
import { getServerConfig, publicContactConfig, canonicalOrigin } from '../server/config.js';
const env = { CONTACT_MODE: 'resend', RESEND_API_KEY: 'unit-test-key', CONTACT_FROM: 'Sender <sender@example.test>', TURNSTILE_SITE_KEY: 'unit-test-public', TURNSTILE_SECRET_KEY: 'unit-test-secret', ALLOWED_ORIGINS: 'https://site.example.test' };
const payload = { name: 'Test User', email: 'user@example.test', message: 'A test enquiry that will not be sent.', topic: 'storm', consent: true, website: '', locale: 'en', token: 'test-token', requestId: '7df0af03-f289-42c3-943d-b6b383aaf467' };
const make = (body = payload, headers = {}, method = 'POST') => new Request('https://site.example.test/api/contact', { method, headers: { 'Content-Type': 'application/json', Origin: 'https://site.example.test', ...headers }, ...(method === 'POST' ? { body: typeof body === 'string' ? body : JSON.stringify(body) } : {}) });
const never = () => { throw new Error('Unexpected provider call'); };
test('default config is mailto', () => assert.deepEqual(publicContactConfig({}), { mode: 'mailto', siteKey: null }));
test('public config excludes secrets', () => { const s = JSON.stringify(publicContactConfig(env)); assert.ok(!s.includes(env.RESEND_API_KEY)); assert.ok(!s.includes(env.TURNSTILE_SECRET_KEY)); });
test('NOT PROVIDED is inactive', () => assert.equal(getServerConfig({ ...env, RESEND_API_KEY: 'NOT PROVIDED' }).enabled, false));
test('origin required', () => assert.equal(getServerConfig({ ...env, ALLOWED_ORIGINS: '' }).enabled, false));
test('normalizes origin', () => assert.equal(canonicalOrigin('https://site.example.test/path'), 'https://site.example.test'));
test('invalid origin protocol', () => assert.equal(canonicalOrigin('javascript:alert(1)'), ''));
test('GET makes no provider call', async () => assert.equal((await handleContact(make(null, {}, 'GET'), { env, fetcher: never })).status, 200));
test('invalid HTTP method', async () => assert.equal((await handleContact(make(null, {}, 'DELETE'), { env, fetcher: never })).status, 405));
test('unconfigured fails closed', async () => assert.equal((await handleContact(make(), { env: {}, fetcher: never })).status, 503));
test('foreign origin rejected', async () => assert.equal((await handleContact(make(payload, { Origin: 'https://evil.example.test' }), { env, fetcher: never })).status, 403));
test('suffix spoof rejected', async () => assert.equal((await handleContact(make(payload, { Origin: 'https://site.example.test.evil.test' }), { env, fetcher: never })).status, 403));
test('MIME enforced', async () => assert.equal((await handleContact(make(payload, { 'Content-Type': 'text/plain' }), { env, fetcher: never })).status, 415));
test('invalid JSON', async () => assert.equal((await handleContact(make('{bad'), { env, fetcher: never })).status, 400));
test('actual body bytes bounded', async () => assert.equal((await handleContact(make('a'.repeat(20001)), { env, fetcher: never })).status, 413));
test('consent required before providers', async () => assert.equal((await handleContact(make({ ...payload, consent: false }), { env, fetcher: never })).status, 400));
test('honeypot before providers', async () => assert.equal((await handleContact(make({ ...payload, website: 'https://bot.test' }), { env, fetcher: never })).status, 400));
test('request ID validated', async () => assert.equal((await handleContact(make({ ...payload, requestId: '' }), { env, fetcher: never })).status, 400));
test('token missing', async () => assert.equal((await handleContact(make({ ...payload, token: '' }), { env, fetcher: never })).status, 400));
for (const [label, d] of [['bad token', { success: false }], ['bad hostname', { success: true, hostname: 'evil.test', action: 'enquiry' }], ['bad action', { success: true, hostname: 'site.example.test', action: 'login' }]])
    test(`verification rejects ${label}`, async () => { let n = 0; const fetcher = async () => { n++; return Response.json(d); }; assert.equal((await handleContact(make(), { env, fetcher })).status, 400); assert.equal(n, 1); });
test('fixed recipient and plain-text content', async () => { const calls = []; const fetcher = async (url, options) => { calls.push({ url, options }); return url.includes('siteverify') ? Response.json({ success: true, hostname: 'site.example.test', action: 'enquiry' }) : Response.json({ id: 'mock-id' }); }; const r = await handleContact(make({ ...payload, to: 'attacker@example.test' }), { env, fetcher }); assert.equal(r.status, 200); assert.equal(calls.length, 2); const email = JSON.parse(calls[1].options.body); assert.deepEqual(email.to, ['MaximusGroup@gmail.com']); assert.equal(email.reply_to, payload.email); assert.equal(email.html, undefined); assert.ok(calls[1].options.headers['Idempotency-Key'].startsWith('maximus-boats/')); });
test('provider errors do not leak secrets', async () => { const fetcher = async (url) => url.includes('siteverify') ? Response.json({ success: true, hostname: 'site.example.test', action: 'enquiry' }) : Response.json({ error: env.RESEND_API_KEY }, { status: 401 }); const r = await handleContact(make(), { env, fetcher }); assert.equal(r.status, 502); assert.ok(!(await r.text()).includes(env.RESEND_API_KEY)); });
test('timeout is failure', async () => assert.equal((await handleContact(make(), { env, fetcher: async () => { throw new Error('timeout'); } })).status, 502));
