/** Build-time rendering helpers; untrusted strings are escaped. */
export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function localize(html, locale, values) {
    let output = html.replace(/<([a-z][a-z0-9-]*)(\b[^>]*\bdata-en="([^"]*)"[^>]*\bdata-ru="([^"]*)"[^>]*)>[^<]*<\/\1>/gi, (all, tag, attrs, en, ru) => `<${tag}${attrs}>${locale === 'ru' ? ru : en}</${tag}>`);
    output = output.replace(/<img\b[^>]*>/gi, tag => { const alt = tag.match(new RegExp('data-alt-' + locale + '="([^"]*)"')); return alt ? tag.replace(/\balt="[^"]*"/, `alt="${alt[1]}"`) : tag; });
    return output.replace(/\{\{([a-zA-Z]+)\}\}/g, (_, key) => { if (!(key in values))
        throw new Error('Missing template value ' + key); return escapeHTML(values[key]); });
}
export function collection(models, locale) {
    const ru = locale === 'ru';
    const titles = Object.keys(models);
    return `<section class="section" id="projects"><div class="container"><div class="section-heading"><div><span class="eyebrow">01 / ${ru ? 'КОЛЛЕКЦИЯ ПРОЕКТОВ' : 'THE COLLECTION'}</span><h2>${ru ? 'Разный характер.<br>Точный замысел.' : 'Distinct by design.'}</h2></div><p>${ru ? 'Парусно-моторная яхта, частные моторные яхты и многоцелевые катера. Выберите проект под вашу задачу.' : 'Motor sailers. Private yachts. Multipurpose craft. Find the project that matches your purpose.'}</p></div><div data-tabs><div class="collection-tabs" role="tablist" aria-label="${ru ? 'Выбор модели' : 'Choose a model'}">${titles.map((id, i) => `<button type="button" role="tab" id="tab-${id}" data-tab="${id}" aria-selected="${!i}" aria-controls="panel-${id}" tabindex="${i ? -1 : 0}"><span>0${i + 1}</span>${models[id].name}</button>`).join('')}</div>${titles.map((id, i) => { const p = models[id], t = p[locale]; return `<article class="collection-panel" data-panel="${id}" id="panel-${id}" role="tabpanel" aria-labelledby="tab-${id}" tabindex="0" ${i ? 'hidden' : ''}><figure class="collection-image"><img src="${p.image}" alt="${p.name} — ${ru ? 'проектная визуализация' : 'project visual'}" loading="lazy"><figcaption>${ru ? 'ПРОЕКТНАЯ ВИЗУАЛИЗАЦИЯ' : 'PROJECT VISUAL'}</figcaption></figure><div class="collection-info"><span class="eyebrow">${escapeHTML(t.subtitle)}</span><h3>${p.name}</h3><p>${escapeHTML(t.description)}</p><dl class="collection-specs">${t.specs.slice(0, 4).map(s => `<div><dt>${escapeHTML(s[0])}</dt><dd>${escapeHTML(s[1])}</dd></div>`).join('')}</dl><a class="button" href="/${locale}/projects/${id}/">${ru ? 'Изучить проект' : 'Explore project'}<span class="arrow">↗</span></a></div></article>`; }).join('')}</div><p class="collection-note">${ru ? 'Каталожные и проектные параметры. Наличие, окончательная спецификация, цена и сроки передачи подтверждаются индивидуально.' : 'Catalogue and design particulars. Current availability, final specification, price and delivery are confirmed individually.'}</p><noscript>${titles.map(id => `<a href="/${locale}/projects/${id}/">${models[id].name}</a>`).join(' / ')}</noscript></div></section>`;
}
export function projectPage(model, id, locale) { const ru = locale === 'ru', t = model[locale]; return `<section class="section"><div class="container"><a href="/${locale}/#projects" class="text-link">← ${ru ? 'Вернуться к коллекции' : 'Back to the collection'}</a><div class="detail-heading"><div><span class="eyebrow">${escapeHTML(t.subtitle)}</span><h1>${model.name}</h1></div><p>${escapeHTML(t.description)}</p></div><img class="detail-main-img" src="${model.image}" alt="${model.name} / ${ru ? 'проектная визуализация' : 'project visual'}" fetchpriority="high"><div class="detail-layout"><h2>${ru ? 'Параметры проекта' : 'Project particulars'}</h2><dl class="collection-specs">${t.specs.map(x => `<div><dt>${escapeHTML(x[0])}</dt><dd>${escapeHTML(x[1])}</dd></div>`).join('')}</dl></div><p class="source-note">${escapeHTML(t.note)}</p>${model.extra ? `<div class="section"><img class="detail-asset" src="${model.extra}" alt="${escapeHTML(t.extraLabel)}" loading="lazy"><p class="collection-note">${escapeHTML(t.extraLabel)}</p></div>` : ''}<div class="actions" style="margin-top:30px"><a class="button primary" href="#contact" data-select-model="${model.name}">${escapeHTML(t.cta)}<span class="arrow">↗</span></a></div></div></section>`; }
export function privacy(locale) { const ru = locale === 'ru'; return `<section class="section"><div class="container legal-copy"><h1>${ru ? 'Конфиденциальность.' : 'Privacy notice.'}</h1><p>MAXIMUS.BOATS / 26 September 2026</p><h2>${ru ? 'Ваш запрос' : 'Your enquiry'}</h2><p>${ru ? 'Коммерческие обращения адресованы MAXIMUS VEGAS L.L.C-FZ. Контакты инвестиционного клуба размещены отдельно. По умолчанию форма подготавливает письмо в вашем почтовом приложении, не отправляет и не сохраняет его автоматически.' : 'Commercial enquiries are addressed to MAXIMUS VEGAS L.L.C-FZ. The investment club has separate contacts. By default the form prepares a message in your email application; it does not send or store it automatically.'}</p><h2>${ru ? 'Серверная отправка' : 'Server delivery'}</h2><p>${ru ? 'При отдельно настроенной серверной отправке имя, email, тема, сообщение и согласие передаются серверному обработчику и почтовому сервису Resend. Cloudflare Turnstile проверяет автоматизированные запросы. Приложение не использует базу данных. Хостинг и почтовые провайдеры могут обрабатывать технические журналы; сроки хранения должны быть отдельно установлены оператором.' : 'When separately configured, server delivery transmits your name, email, topic, message and consent to the endpoint and the Resend email service. Cloudflare Turnstile checks automated requests. The application has no database. Hosting and email providers may process technical logs; retention periods must be separately established by the operator.'}</p><p>${ru ? 'Не отправляйте через открытую форму паспорта, банковские сведения или секретные чертежи. По вопросам обработки данных:' : 'Do not use the public form for passports, banking data or confidential drawings. For data-processing enquiries:'} <a href="mailto:{{commercialEmail}}">{{commercialEmail}}</a>.</p></div></section>`; }
