import { initNavigation } from './modules/navigation.js';
import { initTabs } from './modules/tabs.js';
import { initDialogs } from './modules/dialogs.js';
import { initEnquiry } from './modules/enquiry.js';
import { initGallery } from './modules/gallery.js';
initNavigation();
initTabs();
initDialogs();
initEnquiry();
initGallery();
